# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/jodalyst/vivado/spi_st7735/spi_st7735.cache/wt [current_project]
set_property parent.project_path /home/jodalyst/vivado/spi_st7735/spi_st7735.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:cmod_a7-35t:part0:1.1 [current_project]
set_property ip_output_repo /home/jodalyst/vivado/spi_st7735/spi_st7735.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/jodalyst/vivado/spi_st7735/spi_st7735.srcs/sources_1/imports/new/dimmer.v
  /home/jodalyst/vivado/spi_st7735/spi_st7735.srcs/sources_1/imports/new/spi_master.v
  /home/jodalyst/vivado/spi_st7735/spi_st7735.srcs/sources_1/new/main.v
}
read_ip -quiet /home/jodalyst/vivado/spi_st7735/spi_st7735.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/jodalyst/vivado/spi_st7735/spi_st7735.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/jodalyst/vivado/spi_st7735/spi_st7735.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/jodalyst/vivado/spi_st7735/spi_st7735.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files /home/jodalyst/vivado/spi_st7735/spi_st7735.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jodalyst/vivado/spi_st7735/spi_st7735.srcs/constrs_1/imports/XDC/CmodA7_Master.xdc
set_property used_in_implementation false [get_files /home/jodalyst/vivado/spi_st7735/spi_st7735.srcs/constrs_1/imports/XDC/CmodA7_Master.xdc]


synth_design -top main -part xc7a35tcpg236-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
